# Generated by Django 5.2.8 on 2025-11-11 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Básico', 'Básico'), ('Medio', 'Medio'), ('Avanzado', 'Avanzado')], max_length=10)),
                ('was_won', models.BooleanField()),
                ('time_taken', models.FloatField()),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_victories', models.IntegerField(default=0)),
                ('total_defeats', models.IntegerField(default=0)),
                ('total_games_played', models.IntegerField(default=0)),
                ('total_time_seconds', models.FloatField(default=0.0)),
                ('games_basic', models.IntegerField(default=0)),
                ('games_medium', models.IntegerField(default=0)),
                ('games_advanced', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
